version: '2'

services:
  explorer:
    build: .
    image: explorer
    ports:
      - "4000:3000"
    command: ["npm", "run", "dev-start"]
    volumes:
     - ./views:/explorer/views
     - ./public:/explorer/public
     - ./utils:/explorer/utils
     - ./data:/explorer/data
     - ./routes:/explorer/routes
     - data-volume:/data-volume

volumes:
  data-volume:
    external: true
