version: '3.2'

services:
  explorer:
    build: .
    image: explorer
    ports:
      - "3000:3000"
    command: ["npm", "start"]
    volumes:
      - data-volume:/data-volume
  # ticketledger:
  #   build:
  #     context: ../passage-network-hapi-react/packages/passagex-ticketledger
  #   image: passagex/ticketledger
  #   ports:
  #     - "8545:8545"
  #     - "30303:30303"
  #   volumes:
  #     - data-volume:/data-volume

volumes:
   data-volume:
     external: true
