version: '3.2'

services:
  explorer:
    build: .
    image: explorer
    ports:
      - "3000:3000"
    command: ["npm", "start"]
    volumes:
      - data-volume:/data-volume
    restart: always

volumes:
   data-volume:
     external: true
